import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const alpina = localFont({
  src: [
    {
      path: "../fonts/alpina-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/alpina-italics.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-alpina",
});

const alpina_condensed = localFont({
  src: [
    {
      path: "../fonts/alpina-condensed-normal.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/alpina-condensed-italics.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-alpina-condensed",
});

const oracle = localFont({
  src: "../fonts/oracle-regular.woff2",
  variable: "--font-oracle",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alpina.variable} ${oracle.variable} ${alpina_condensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
